# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8b75c5a4d6989be7ad0c197eafe0645"
name = "AIPostPurchaseRevenueOptimizer"
application_url = "https://astrology-paying-salaries-exclusive.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://astrology-paying-salaries-exclusive.trycloudflare.com/shopify/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
